# Álgebra linear em Julia

## Operações básicas

Primeiro, vamos construir uma matriz 3x3 com entradas entre 1 e 4 escolhidas aleatoriamente:

In [1]:
A = rand(1:4, 3, 3)

3×3 Array{Int64,2}:
 1  2  1
 1  2  2
 2  2  3

Agora, vamos construir um vetor com 3 coordenadas todas iguais a 1:

In [2]:
v = fill(1.0, (3))

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

### Multiplicação

In [3]:
b = A*v

3-element Array{Float64,1}:
 4.0
 5.0
 7.0

### Transposição

A matriz `transpose(A)` é a transposta de `A`:

In [4]:
transpose(A)

3×3 LinearAlgebra.Transpose{Int64,Array{Int64,2}}:
 1  1  2
 2  2  2
 1  2  3

A matriz `A'` é a adjunta de `A`, ou seja, a transposta conjugada de `A`, que coincide com a transposta de `A` (`transpose(A)`) quando `A` é real.

In [5]:
A'

3×3 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1  1  2
 2  2  2
 1  2  3

### Multiplicação pela transposta

Em Julia, podemos escrever simplesmente `A'A` em vez de `(A')*A`:

In [6]:
A'A

3×3 Array{Int64,2}:
 6   8   9
 8  12  12
 9  12  14

In [7]:
(A')*A

3×3 Array{Int64,2}:
 6   8   9
 8  12  12
 9  12  14

## Resolvendo sistemas de equações lineares

O problema $Ax = b$ pode ser resolvido usando a função `\`.

In [8]:
x = A\b

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

## Matrizes com estrutura especial

In [9]:
using LinearAlgebra

In [10]:
n = 1000
A = randn(n,n);

Frequentemente, é possível inferir a estrutura de uma matriz:

In [11]:
Asim = A + A'
issymmetric(Asim)

true

Todavia, muitas vezes os arredondamentos numéricos atrapalham:

In [12]:
Asim_ruido = copy(Asim)
ruido = 5eps()
println("ruido = $ruido")
Asim_ruido[1,2] += ruido
issymmetric(Asim_ruido)

ruido = 1.1102230246251565e-15


false

O comando acima inseriu um ruído da ordem de 10<sup>-15</sup> no elemento (1,2) da matriz `Asim`.

A linguagem Julia permite que declaremos explicitamente a estrutura de uma matriz usando, por exemplo, `Diagonal`, `Triangular`, `Symmetric`, `Hermitian`, `Tridiagonal` e `SymTridiagonal`.

In [13]:
Asim_explicita = Symmetric(Asim_ruido)
issymmetric(Asim_explicita)

true

Vamos comparar quanto tempo leva para a Julia calcular os autovalores de `Asim`, `Asim_ruido` e `Asim_explicita`.

In [14]:
@time eigvals(Asim);

  0.383190 seconds (858.56 k allocations: 49.301 MiB, 3.22% gc time)


In [15]:
@time eigvals(Asim_ruido);

  0.767084 seconds (18 allocations: 7.921 MiB, 0.97% gc time)


In [16]:
@time eigvals(Asim_explicita);

  0.098052 seconds (6.66 k allocations: 8.297 MiB)


Observamos que o cálculo com `Asim_explicita` (onde usamos `Symmetric()`) foi muitas vezes mais rápido do que o cálculo com `Asim_ruido`.

## Um problema grande

Usando os tipos `Tridiagonal` e `SymTridiagonal`, podemos armazenar matrizes de forma eficiente.
Isso torna possível fazer cálculos com matrizes muito grandes.
Por exemplo, não seria possível resolver em um laptop o seguinte problema se armazenássemos a matriz usando o tipo `Array`.

In [17]:
n = 1_000_000;
A = SymTridiagonal(randn(n), randn(n-1));
@time eigmax(A)

  0.778396 seconds (573.55 k allocations: 180.880 MiB, 9.32% gc time)


6.364223488857943

O cálculo acima demorou menos de 1 segundo.
Explicamos a seguir o significado dos comandos.

O comando abaixo cria uma matriz simétrica 6x6 especificando 6 números aleatórios na diagonal e 5 números aleatórios na diagonal secundária.

In [18]:
B = SymTridiagonal(randn(6), randn(6-1))

6×6 SymTridiagonal{Float64,Array{Float64,1}}:
 -1.42893  -0.74123     ⋅          ⋅          ⋅         ⋅      
 -0.74123  -1.00566    0.394494    ⋅          ⋅         ⋅      
   ⋅        0.394494   0.122927  -0.899586    ⋅         ⋅      
   ⋅         ⋅        -0.899586   0.504053  -0.221936   ⋅      
   ⋅         ⋅          ⋅        -0.221936   0.199231  1.46452 
   ⋅         ⋅          ⋅          ⋅         1.46452   0.778833

Portanto, a matriz `A` acima tem estrutura semelhante mas é de ordem **1 milhão x 1 milhão**:

In [19]:
A

1000000×1000000 SymTridiagonal{Float64,Array{Float64,1}}:
 -0.354246   1.11562     ⋅        …    ⋅          ⋅          ⋅      
  1.11562   -0.226126  -0.987676       ⋅          ⋅          ⋅      
   ⋅        -0.987676   0.135718       ⋅          ⋅          ⋅      
   ⋅          ⋅         0.110276       ⋅          ⋅          ⋅      
   ⋅          ⋅          ⋅             ⋅          ⋅          ⋅      
   ⋅          ⋅          ⋅        …    ⋅          ⋅          ⋅      
   ⋅          ⋅          ⋅             ⋅          ⋅          ⋅      
   ⋅          ⋅          ⋅             ⋅          ⋅          ⋅      
   ⋅          ⋅          ⋅             ⋅          ⋅          ⋅      
   ⋅          ⋅          ⋅             ⋅          ⋅          ⋅      
   ⋅          ⋅          ⋅        …    ⋅          ⋅          ⋅      
   ⋅          ⋅          ⋅             ⋅          ⋅          ⋅      
   ⋅          ⋅          ⋅             ⋅          ⋅          ⋅      
  ⋮                               ⋱          

O comando `randn(6)` cria uma lista de 6 números aleatórios.

In [20]:
randn(6)

6-element Array{Float64,1}:
 -1.3934484752355702
 -1.1620924895713112
 -1.5374341827044993
 -1.0859109660548516
 -0.4609719981587992
 -0.2796215589930371

O comando `eigmax(A)` calcula o maior autovalor de `A`.

Com os comandos a seguir, podemos ler as documentações sobre as funções (lembre da dica de copiar a descrição e colar em https://translate.google.com):

In [21]:
?eigmax

search: eigmax



```
eigmax(A; permute::Bool=true, scale::Bool=true)
```

Return the largest eigenvalue of `A`. The option `permute=true` permutes the matrix to become closer to upper triangular, and `scale=true` scales the matrix by its diagonal elements to make rows and columns more equal in norm. Note that if the eigenvalues of `A` are complex, this method will fail, since complex numbers cannot be sorted.

# Examples

```jldoctest
julia> A = [0 im; -im 0]
2×2 Array{Complex{Int64},2}:
 0+0im  0+1im
 0-1im  0+0im

julia> eigmax(A)
1.0

julia> A = [0 im; -1 0]
2×2 Array{Complex{Int64},2}:
  0+0im  0+1im
 -1+0im  0+0im

julia> eigmax(A)
ERROR: DomainError with Complex{Int64}[0+0im 0+1im; -1+0im 0+0im]:
`A` cannot have complex eigenvalues.
Stacktrace:
[...]
```


In [22]:
?randn

search: randn lowrankdowndate lowrankdowndate! RankDeficientException rand



```
randn([rng=GLOBAL_RNG], [T=Float64], [dims...])
```

Generate a normally-distributed random number of type `T` with mean 0 and standard deviation 1. Optionally generate an array of normally-distributed random numbers. The `Base` module currently provides an implementation for the types [`Float16`](@ref), [`Float32`](@ref), and [`Float64`](@ref) (the default), and their [`Complex`](@ref) counterparts. When the type argument is complex, the values are drawn from the circularly symmetric complex normal distribution.

# Examples

```jldoctest
julia> rng = MersenneTwister(1234);

julia> randn(rng, ComplexF64)
0.6133070881429037 - 0.6376291670853887im

julia> randn(rng, ComplexF32, (2, 3))
2×3 Array{Complex{Float32},2}:
 -0.349649-0.638457im  0.376756-0.192146im  -0.396334-0.0136413im
  0.611224+1.56403im   0.355204-0.365563im  0.0905552+1.31012im
```
