# Álgebra linear em Julia

## Operações básicas

Primeiro, vamos construir uma matriz 3x3 com entradas entre 1 e 4 escolhidas aleatoriamente:

In [1]:
A = rand(1:4, 3, 3)

3×3 Array{Int64,2}:
 3  3  4
 4  4  2
 1  4  3

Agora, vamos construir um vetor com 3 coordenadas todas iguais a 1:

In [2]:
v = fill(1.0, (3))

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

### Multiplicação

In [3]:
b = A*v

3-element Array{Float64,1}:
 10.0
 10.0
  8.0

### Transposição

A matriz `transpose(A)` é a transposta de `A`:

In [4]:
transpose(A)

3×3 LinearAlgebra.Transpose{Int64,Array{Int64,2}}:
 3  4  1
 3  4  4
 4  2  3

A matriz `A'` é a adjunta de `A`, ou seja, a transposta conjugada de `A`, que coincide com a transposta de `A` quando `A` é real.

In [5]:
A'

3×3 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 3  4  1
 3  4  4
 4  2  3

### Multiplicação pela transposta

Em Julia, podemos escrever simplesmente `A'A` em vez de `(A')*A`:

In [6]:
A'A

3×3 Array{Int64,2}:
 26  29  23
 29  41  32
 23  32  29

In [7]:
(A')*A

3×3 Array{Int64,2}:
 26  29  23
 29  41  32
 23  32  29

## Resolvendo sistemas de equações lineares

O problema $Ax = b$ pode ser resolvido usando a função `\`.

In [8]:
x = A\b

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

## Matrizes com estrutura especial

In [9]:
using LinearAlgebra

In [10]:
n = 1000
A = randn(n,n);

Frequentemente, é possível inferir a estrutura de uma matriz:

In [11]:
Asim = A + A'
issymmetric(Asim)

true

Todavia, muitas vezes os arredondamentos numéricos atrapalham:

In [12]:
Asim_ruido = copy(Asim)
ruido = 5eps()
println("ruido = $ruido")
Asim_ruido[1,2] += ruido
issymmetric(Asim_ruido)

ruido = 1.1102230246251565e-15


false

O comando acima inseriu um ruído da ordem de 10<sup>-15</sup> no elemento (1,2) da matriz `Asim`.

A linguagem Julia permite que declaremos explicitamente a estrutura de uma matriz usando, por exemplo, `Diagonal`, `Triangular`, `Symmetric`, `Hermitian`, `Tridiagonal` e `SymTridiagonal`.

In [13]:
Asim_explicita = Symmetric(Asim_ruido)
issymmetric(Asim_explicita)

true

Vamos comparar quanto tempo leva para a Julia calcular os autovalores de `Asim`, `Asim_ruido` e `Asim_explicita`.

In [14]:
@time eigvals(Asim);

  1.245386 seconds (679.55 k allocations: 42.589 MiB, 1.05% gc time)


In [15]:
@time eigvals(Asim_ruido);

  9.227904 seconds (13 allocations: 7.920 MiB)


In [16]:
@time eigvals(Asim_explicita);

  0.652045 seconds (6.82 k allocations: 8.354 MiB)


Observamos que o cálculo com `Asim_explicita` (onde usamos `Symmetric()`) foi muitas vezes mais rápido do que o cálculo com `Asim_ruido`.

## Um problema grande

Usando os tipos `Tridiagonal` e `SymTridiagonal`, podemos armazenar matrizes de forma eficiente.
Isso torna possível fazer cálculos com matrizes muito grandes.
Por exemplo, não seria possível resolver em um laptop o seguinte problema se armazenássemos a matriz usando o tipo `Array`.

In [17]:
n = 1_000_000;
A = SymTridiagonal(randn(n), randn(n-1));
@time eigmax(A)

  0.886968 seconds (453.00 k allocations: 206.245 MiB, 5.00% gc time)


6.209671428337593

O cálculo acima demorou menos de 1 segundo.
Explicamos a seguir o significado dos comandos.

O comando abaixo cria uma matriz simétrica 6x6 especificando 6 números aleatórios na diagonal e 5 números aleatórios na diagonal secundária.

In [18]:
B = SymTridiagonal(randn(6), randn(6-1))

6×6 SymTridiagonal{Float64,Array{Float64,1}}:
 -0.561416  -1.06418    ⋅         ⋅          ⋅         ⋅ 
 -1.06418   -2.13597  -0.48408    ⋅          ⋅         ⋅ 
   ⋅        -0.48408   0.547315  0.985968    ⋅         ⋅ 
   ⋅          ⋅        0.985968  0.129725   0.661481   ⋅ 
   ⋅          ⋅         ⋅        0.661481  -0.806141  0.90259
   ⋅          ⋅         ⋅         ⋅         0.90259   0.234341

Portanto, a matriz `A` acima tem estrutura semelhante mas é de ordem **1 milhão x 1 milhão**:

In [19]:
A

1000000×1000000 SymTridiagonal{Float64,Array{Float64,1}}:
  0.548335  -0.276958     ⋅         …    ⋅          ⋅          ⋅ 
 -0.276958   0.169436    0.0487422       ⋅          ⋅          ⋅ 
   ⋅         0.0487422  -0.397755        ⋅          ⋅          ⋅ 
   ⋅          ⋅          1.39036         ⋅          ⋅          ⋅ 
   ⋅          ⋅           ⋅              ⋅          ⋅          ⋅ 
   ⋅          ⋅           ⋅         …    ⋅          ⋅          ⋅ 
   ⋅          ⋅           ⋅              ⋅          ⋅          ⋅ 
   ⋅          ⋅           ⋅              ⋅          ⋅          ⋅ 
   ⋅          ⋅           ⋅              ⋅          ⋅          ⋅ 
   ⋅          ⋅           ⋅              ⋅          ⋅          ⋅ 
   ⋅          ⋅           ⋅         …    ⋅          ⋅          ⋅ 
   ⋅          ⋅           ⋅              ⋅          ⋅          ⋅ 
   ⋅          ⋅           ⋅              ⋅          ⋅          ⋅ 
  ⋮                                 ⋱                        
   ⋅          ⋅       

O comando `randn(6)` cria uma lista de 6 números aleatórios.

In [20]:
randn(6)

6-element Array{Float64,1}:
  0.5058495630849918
 -0.18242505770019732
 -0.2703450484756285
 -1.2899348096803827
  0.5949947209101717
 -0.9785539596756307

O comando `eigmax(A)` calcula o maior autovalor de `A`.

Com os comandos a seguir, podemos ler as documentações sobre as funções (lembre da dica de copiar a descrição e colar em https://translate.google.com):

In [21]:
?eigmax

search: 

eigmax



```
eigmax(A; permute::Bool=true, scale::Bool=true)
```

Return the largest eigenvalue of `A`. The option `permute=true` permutes the matrix to become closer to upper triangular, and `scale=true` scales the matrix by its diagonal elements to make rows and columns more equal in norm. Note that if the eigenvalues of `A` are complex, this method will fail, since complex numbers cannot be sorted.

# Examples

```jldoctest
julia> A = [0 im; -im 0]
2×2 Array{Complex{Int64},2}:
 0+0im  0+1im
 0-1im  0+0im

julia> eigmax(A)
1.0

julia> A = [0 im; -1 0]
2×2 Array{Complex{Int64},2}:
  0+0im  0+1im
 -1+0im  0+0im

julia> eigmax(A)
ERROR: DomainError with Complex{Int64}[0+0im 0+1im; -1+0im 0+0im]:
`A` cannot have complex eigenvalues.
Stacktrace:
[...]
```


In [22]:
?randn

search: randn lowrankdowndate lowrankdowndate! RankDeficientException rand



```
randn([rng=GLOBAL_RNG], [T=Float64], [dims...])
```

Generate a normally-distributed random number of type `T` with mean 0 and standard deviation 1. Optionally generate an array of normally-distributed random numbers. The `Base` module currently provides an implementation for the types [`Float16`](@ref), [`Float32`](@ref), and [`Float64`](@ref) (the default), and their [`Complex`](@ref) counterparts. When the type argument is complex, the values are drawn from the circularly symmetric complex normal distribution of variance 1 (corresponding to real and imaginary part having independent normal distribution with mean zero and variance `1/2`).

# Examples

```jldoctest
julia> using Random

julia> rng = MersenneTwister(1234);

julia> randn(rng, ComplexF64)
0.6133070881429037 - 0.6376291670853887im

julia> randn(rng, ComplexF32, (2, 3))
2×3 Array{Complex{Float32},2}:
 -0.349649-0.638457im  0.376756-0.192146im  -0.396334-0.0136413im
  0.611224+1.56403im   0.355204-0.365563im  0.0905552+1.31012im
```
